name: Sphinx Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: uv sync --locked --no-dev --extra docs

    - name: Build docs
      run: |
        cd docs
        uv run make html

    - name: Push to gh-pages branch
      run: |
        cd docs/_build/html
        git init
        git config user.name "ohmyocr"
        git config user.email "ohmyocr@gmail.com"
        git add .
        git commit -m "pages"
        git branch -m gh-pages
        git remote add origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/oh-my-ocr/text_renderer.git
        git push origin gh-pages -f
